<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-android;net10.0-ios</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ApplicationTitle>Skottie MAUI</ApplicationTitle>
    <ApplicationId>com.skottie.playground.maui</ApplicationId>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" />
    <ProjectReference Include="../../src/Skottie.Mobile.Maui/Skottie.Mobile.Maui.csproj" />
    <MauiAsset Include="../Shared/orbit.json" Link="Resources/Raw/animations/orbit.json" LogicalName="animations/orbit.json" />
    <MauiSplashScreen Include="Resources/Splash/splash.svg" Color="#F2F6FA" BaseSize="128,128" />
    <MauiIcon Include="Resources/AppIcon/appicon.svg" Color="#F2F6FA" />
  </ItemGroup>
</Project>
